#!/usr/bin/env bash

echo "Creating database tamias-ui..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database tamias-ui-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://sage@localhost:5432/tamias-ui-test?sslmode=disable&password=secret_pass..."
pgmgr -c ".pgmgr.test.json" db migrate
